### ISSUE TITLE
Unable to build UEFIDump after 59a6f2 commit

### ISSUE THREAD

**Issue by laptander** [LongSoft/UEFITool#59]
You have deleted fitParser.h and fitParser.cpp in 59a6f2 commit.
But you did not edit UEFIDump/uefidump.h. [UEFIDump/uefidump.h](https://github.com/LongSoft/UEFITool/blob/new_engine/UEFIDump/uefidump.h#L22) includes fitParser.h.
I tryed to comment this line, but it was unable to build. Please fix.

**Comment by NikolajSchlej** [comment]
Fixed in the latest commit. Sorry for forgetting about it, I've fixed UEFIExtract, but just completely forgot that UEFIDump needs porting too.

**Comment by laptander** [comment]
Still cannot build. Something wrong with std namespace. [Building log](https://gist.github.com/laptander/9e57e3aebfff0402e746999918f08574).

**Comment by NikolajSchlej** [comment]
Can you also provide CMake log? 
I'm testing my builds in OSX with CLang (AppleClang 6.0.0.6000057), and it's totally fine for me.

**Comment by NikolajSchlej** [comment]
Also, please also try the latest commit, I've added the include file where std::count and std::reverse are expected to be defined. Should add GCC to my build testing or just finally setup CI properly.

**Comment by laptander** [comment]
Now it builds correctly, thanks.
